# Generated by Django 5.1.3 on 2024-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0002_alter_bagsmodel_description_alter_bagsmodel_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagsmodel',
            name='image',
            field=models.ImageField(default='../media/news/newsdefault.webp', upload_to=''),
        ),
    ]
