# Generated by Django 5.1.3 on 2024-11-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0008_alter_bagsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='image',
            field=models.ImageField(default='', upload_to='news/'),
        ),
    ]
