# Generated by Django 5.1.3 on 2024-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0010_alter_bagsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
