# Generated by Django 5.1.3 on 2024-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0012_alter_bagsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
