# Generated by Django 5.1.3 on 2024-11-08 15:01

import bagsApp.models
import bagsApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0013_alter_bagsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='image',
            field=models.ImageField(default='newsdefault.webp', storage=bagsApp.storage.OverwriteStorage, upload_to=bagsApp.models.BagsModel.upload_location),
        ),
    ]
