# Generated by Django 5.1.3 on 2024-11-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0019_alter_bagsmodel_slugbag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagsmodel',
            old_name='slugbag',
            new_name='slug',
        ),
    ]
