# Generated by Django 5.1.3 on 2024-11-14 12:05

import bagsApp.fields
import bagsApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0021_bagsphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsphotos',
            name='images',
            field=bagsApp.fields.WEBPField(upload_to=bagsApp.models.BagsPhotos.upload_location),
        ),
    ]
