# Generated by Django 5.1.3 on 2024-11-08 13:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='bagsmodel',
            name='material',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Algodon', 'Algodon'), ('Hilo', 'Hilo'), ('Trapillo', 'Trapillo'), ('Lana', 'Lana')], max_length=50),
        ),
    ]
