# Generated by Django 5.1.3 on 2024-11-08 14:03

import bagsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0009_alter_bagsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='image',
            field=models.ImageField(default='newsdefault.webp', upload_to=bagsApp.models.BagsModel.upload_location),
        ),
    ]
