# Generated by Django 5.1.3 on 2024-11-08 15:52

import bagsApp.fields
import bagsApp.models
import bagsApp.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0014_alter_bagsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='image',
            field=bagsApp.fields.WEBPField(default='newsdefault.webp', storage=bagsApp.storage.OverwriteStorage, upload_to=bagsApp.models.BagsModel.upload_location),
        ),
    ]
