# Generated by Django 5.1.3 on 2024-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0015_alter_bagsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagsmodel',
            name='slugbag',
            field=models.SlugField(default='news'),
        ),
    ]
