# Generated by Django 5.1.3 on 2024-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsApp', '0018_alter_bagsmodel_slugbag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagsmodel',
            name='slugbag',
            field=models.SlugField(default=''),
        ),
    ]
