# Generated by Django 5.1.3 on 2024-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='imagen',
            field=models.ImageField(default='../media/news/newsdefault.webp', upload_to=''),
        ),
    ]
