# Generated by Django 5.1.3 on 2024-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_remove_newsmodel_imagen_newsmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='slugnews',
            field=models.SlugField(default='news'),
        ),
    ]
