# Generated by Django 5.1.3 on 2024-11-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0006_alter_newsmodel_slugnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slugnews',
            field=models.SlugField(),
        ),
    ]
