# Generated by Django 5.1.3 on 2024-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_alter_newsmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='imagen',
            field=models.ImageField(default='newsdefault.webp', upload_to=''),
        ),
    ]
