# Generated by Django 5.1.3 on 2024-11-08 17:08

import bagsApp.fields
import bagsApp.storage
import newsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_alter_newsmodel_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='imagen',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='image',
            field=bagsApp.fields.WEBPField(default='newsdefault.webp', storage=bagsApp.storage.OverwriteStorage, upload_to=newsApp.models.newsModel.upload_location),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
