# Generated by Django 5.1.3 on 2024-11-12 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_alter_newsmodel_slugnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='slugnews',
            new_name='slug',
        ),
    ]
