# Generated by Django 5.1.3 on 2024-11-12 19:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_rename_slugnews_newsmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
